[package]
name = "signers"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
eigenda = { workspace = true }
eth = { workspace = true }
alloy = { workspace = true, features = ["signer-aws"] }
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-kms = { workspace = true }
async-trait = { workspace = true }
k256 = { workspace = true, features = ["pkcs8"] }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
rust-eigenda-signers = { workspace = true }
thiserror = { workspace = true }

[features]
test-helpers = []
