[package]
name = "types"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[features]
rand = ["dep:rand"]
