[package]
name = "storage"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
num-bigint = { workspace = true }
ports = { workspace = true, features = ["storage"] }
rand = { workspace = true, optional = true }
serde = { workspace = true }
sqlx = { workspace = true, features = [
  "bigdecimal",
  "postgres",
  "runtime-tokio",
  "migrate",
  "macros",
  "tls-rustls",
  "time",
  "chrono",
] }
testcontainers = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
ports = { workspace = true, features = ["storage"] }
hex = { workspace = true }
rand = { workspace = true }
storage = { workspace = true, features = ["test-helpers"] }
tokio = { workspace = true }

[features]
test-helpers = [
  "dep:testcontainers",
  "tokio/sync",
  "dep:rand",
  "ports/test-helpers",
]
