[eth]
chain_id = "anvil"
state_contract_address = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
rpc = "ws://localhost:8545"

[fuel]
graphql_endpoint = "http://localhost:4000"
block_producer_public_key = "0x73dc6cc8cc0041e4924954b35a71a22ccb520664c522198a6d31dc6c945347bb854a39382d296ec64c70d7cea1db75601595e29729f3fbdc7ee9dae66705beb4"

[app]
port = 8080
host = "0.0.0.0"
block_check_interval = "1s"
num_blocks_to_finalize_tx = 12

[app.db]
host = "localhost"
port = 5432
username = "username"
password = "password"
database = "test"
max_connections = 5
use_ssl = false
