[package]
name = "clock"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
services = { workspace = true }

[dev-dependencies]
clock = { workspace = true, features = ["test-helpers"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
test-helpers = []
