[package]
name = "fuel_rpc"
version = "0.1.0"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
fuel-core-client = { workspace = true }
metrics = { workspace = true }
ports = { workspace = true, features = ["fuel"] }
prometheus = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[features]
test-helpers = []
