apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuel-block-committer.fullname" . }}
  labels:
    {{- include "fuel-block-committer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuel-block-committer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuel-block-committer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuel-block-committer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "./fuel-block-committer" ]
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
            - "--db-path"
            - "/mnt/db/db.db3"
          envFrom:
            - configMapRef:
                name: fuel-block-committer
            - secretRef:
                name: fuel-block-committer
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: {{ include "fuel-block-committer.fullname" . }}
              mountPath: "/mnt/db"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fuel-block-committer-vol
          persistentVolumeClaim:
            claimName: {{ include "fuel-block-committer.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
