[package]
name = "ports"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
delegate = { workspace = true, optional = true }
trait-variant = { workspace = true, optional = true }
alloy = { workspace = true, optional = true }
fuel-core-client = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
impl-tools = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true, optional = true }
hex = { workspace = true }
async-trait = { workspace = true, optional = true }
nonempty = { workspace = true }
itertools = { workspace = true, features = ["use_std"] }

[features]
test-helpers = ["dep:mockall", "dep:rand"]
l1 = [
  "dep:async-trait",
  "dep:alloy",
  "dep:futures",
  "dep:thiserror",
  "dep:trait-variant",
]
fuel = [
  "dep:thiserror",
  "dep:fuel-core-client",
  "dep:futures",
  "dep:trait-variant",
]
storage = [
  "dep:trait-variant",
  "dep:impl-tools",
  "dep:thiserror",
  "dep:futures",
  "dep:delegate",
]
clock = []
full = ["l1", "fuel", "storage", "clock"]
