[package]
name = "ports"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true, optional = true }
ethers-core = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
impl-tools = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true, optional = true }

[features]
test-helpers = ["dep:mockall", "dep:rand"]
eth = ["dep:ethers-core", "dep:futures", "dep:thiserror", "dep:async-trait"]
fuel = ["dep:thiserror", "dep:async-trait"]
storage = ["dep:impl-tools", "dep:thiserror", "dep:async-trait"]
full = ["eth", "fuel", "storage"]
