[package]
name = "ports"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
alloy = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
delegate = { workspace = true, optional = true }
fuel-core-client = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
itertools = { workspace = true, features = ["use_std"], optional = true }
mockall = { workspace = true, optional = true }
nonempty = { workspace = true }
rand = { workspace = true, optional = true }
sqlx = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true, optional = true }
trait-variant = { workspace = true, optional = true }

[features]
test-helpers = ["dep:mockall", "dep:rand"]
l1 = [
  "dep:async-trait",
  "dep:alloy",
  "dep:futures",
  "dep:thiserror",
  "dep:trait-variant",
]
fuel = [
  "dep:thiserror",
  "dep:fuel-core-client",
  "dep:futures",
  "dep:trait-variant",
]
storage = [
  "dep:trait-variant",
  "dep:thiserror",
  "dep:futures",
  "dep:delegate",
  "dep:itertools",
]
clock = []
full = ["l1", "fuel", "storage", "clock"]

[dev-dependencies]
rand = { workspace = true, features = ["std", "std_rng"] }
