[package]
name = "ports"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
alloy = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
fuel-core-client = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
impl-tools = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true, optional = true }
validator = { workspace = true, optional = true }
hex = { workspace = true }

[features]
test-helpers = ["dep:mockall", "dep:rand", "validator?/test-helpers"]
l1 = [
  "dep:alloy",
  "dep:futures",
  "dep:thiserror",
  "dep:async-trait",
  "dep:validator",
]
fuel = [
  "dep:thiserror",
  "dep:async-trait",
  "dep:fuel-core-client",
  "dep:validator",
]
storage = ["dep:impl-tools", "dep:thiserror", "dep:async-trait"]
clock = []
full = ["l1", "fuel", "storage", "clock"]
