[package]
name = "storage"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
delegate = { workspace = true, optional = true }
hex = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
metrics = { workspace = true }
num-bigint = { workspace = true }
services = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
  "bigdecimal",
  "postgres",
  "runtime-tokio",
  "migrate",
  "macros",
  "tls-rustls",
  "time",
  "chrono",
  "json"
] }
testcontainers = { workspace = true, optional = true, features = [
  "signal-hook",
  "watchdog",
] }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
hex = { workspace = true }
clock = { workspace = true, features = ["test-helpers"] }
rand = { workspace = true, features = ["small_rng"] }
storage = { workspace = true, features = ["test-helpers"] }
tokio = { workspace = true }

[features]
test-helpers = [
  "dep:testcontainers",
  "tokio/sync",
  "dep:rand",
  "dep:delegate",
]
