[package]
name = "e2e"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }
build = "build.rs"

[build-dependencies]
itertools = { workspace = true, default-features = true }
walkdir = { workspace = true, default-features = true }
reqwest = { workspace = true, default-features = true }
zip = { workspace = true, default-features = true }
anyhow = { workspace = true, default-features = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "process",
  "fs",
] }

[dev-dependencies]
serde = { workspace = true }
ethers = { workspace = true }
rand = { workspace = true, features = ["std"] }
hex = { workspace = true }
portpicker = { workspace = true }
url = { workspace = true }
storage = { workspace = true, features = ["test-helpers"] }
reqwest = { workspace = true, default-features = true }
zip = { workspace = true, default-features = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "process",
  "fs",
] }
anyhow = { workspace = true, default-features = true }
eth = { workspace = true, features = ["test-helpers"] }
fuel = { workspace = true, features = ["test-helpers"] }
ports = { workspace = true, features = ["fuel", "l1"] }
serde_json = { workspace = true }
validator = { workspace = true, features = ["validator"] }
