[package]
name = "e2e"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }
build = "build.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ethers-core = { workspace = true }
hex = { workspace = true }

[build-dependencies]
reqwest = { workspace = true, default-features = true }
zip = { workspace = true, default-features = true }
anyhow = { workspace = true, default-features = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
anyhow = { workspace = true, default-features = true }
eth = { workspace = true, features = ["test-helpers"] }
fuel = { workspace = true, features = ["test-helpers"] }
ports = { workspace = true, features = ["fuel", "l1"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
validator = { workspace = true, features = ["validator"] }
