[package]
name = "eth"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
alloy = { workspace = true, features = [
  "consensus",
  "network",
  "provider-ws",
  "kzg",
  "contract",
  "signer-aws",
  "rpc-types",
  "reqwest-rustls-tls",
] }
async-trait = { workspace = true }
aws-config = { workspace = true, features = ["default"] }
aws-sdk-kms = { workspace = true, features = ["default"] }
delegate = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
metrics = { workspace = true }
ports = { workspace = true, features = ["l1"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
ports = { workspace = true, features = ["l1", "test-helpers"] }
rand = { workspace = true, features = ["small_rng"] }
test-case = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
test-helpers = []
