[package]
name = "fuel"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
fuel-core-client = { workspace = true, features = ["subscriptions"] }
fuel-core-types = { workspace = true, optional = true }
metrics = { workspace = true }
ports = { workspace = true, features = ["fuel"] }
url = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[features]
test-helpers = ["fuel-core-types"]
