[package]
name = "fuel"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }
build = "build.rs"

[dependencies]
cynic = { version = "2.2", features = ["http-reqwest"] }
delegate = { workspace = true }
fuel-core-client = { workspace = true, features = ["subscriptions"] }
futures = { workspace = true }
metrics = { workspace = true }
ports = { workspace = true, features = ["fuel"] }
trait-variant = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[build-dependencies]
fuel-core-client = { workspace = true }

[features]
test-helpers = []
