[package]
name = "benchmarks"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
fuel-block-committer-encoding = { workspace = true }
services = { workspace = true }
test-helpers = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
rand = { workspace = true, features = ["small_rng"] }
criterion = { version = "0.5", features = ["html_reports"] }
num-bigint = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "std",
  "fmt",
  "json",
] }
clock = { workspace = true }

[[bench]]
name = "eigenbundler"
harness = false

[[bench]]
name = "service_bundler"
harness = false

[[bin]]
name = "eigenbundler"
path = "benches/eigenbundler.rs"

[[bin]]
name = "service_bundler"
path = "benches/service_bundler.rs"
