name: 'Docker publish image'

inputs:
  docker_registry:
    default: ghcr.io
    require: true
  image_name:
    require: true
  default_branch:
    default: master
    require: true
  docker_context:
    default: .
    require: true
  docker_platforms:
    require: true
  docker_file:
    default: deployment/Dockerfile
    require: true
  github_token:
    require: true

runs:
  using: 'composite'
  steps:
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
            ${{ inputs.docker_registry }}/${{ inputs.image_name }}
        tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{raw}}
        flavor: |
            latest=${{ github.ref == 'refs/heads/' + inputs.default_branch }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the ghcr.io registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Build and push the image to ghcr.io
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker_context }}
        platforms: ${{ inputs.docker_platforms }}
        file: ${{ inputs.docker_file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
