[package]
name = "validator"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
fuel-core-client = { workspace = true }
fuel-crypto = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
fuel-crypto = { workspace = true, features = ["random"] }
rand = { workspace = true, features = ["std", "std_rng"] }
tai64 = { workspace = true }
validator = { workspace = true, features = ["validator", "test-helpers"] }

[features]
validator = ["dep:fuel-crypto"]
test-helpers = ["validator", "dep:mockall", "dep:rand"]
