{{- if .Values.app.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-service-monitor
  labels:
    release: {{ .Values.app.prometheus.helm_release_name }}
spec:
  selector:
    app: {{ template "fuel-block-committer.name" . }}
    release: {{ .Release.Name }}
  endpoints:
    - path: /metrics
      port: http
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-committer-claim"
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "gp3"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ template "fuel-block-committer.name" . }}
    chart: {{ template "fuel-block-committer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Release.Name }}-committer-service
spec:
  type: NodePort
  selector:
    app: {{ template "fuel-block-committer.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-committer-deployment
  labels:
    app: {{ template "fuel-block-committer.name" . }}
    chart: {{ template "fuel-block-committer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "fuel-block-committer.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fuel-block-committer.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          command: ["./fuel-block-committer"]
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
            - "--db-path"
            - "/mnt/db/db.db3"
          resources: {}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: "{{ .Release.Name }}-committer-volume"
              mountPath: "/mnt/db"
          env:
            - name: ETHEREUM_WALLET_KEY
              value: "{{ .Values.app.ethereum_wallet_key | default false }}"
            - name: ETHEREUM_RPC
              value: "{{ .Values.app.ethereum_rpc }}"
            - name: ETHEREUM_CHAIN
              value: "{{ .Values.app.ethereum_chain_id }}"
            - name: FUEL_GRAPHQL_ENDPOINT
              value: "{{ .Values.app.fuel_graphql_endpoint }}"
            - name: STATE_CONTRACT_ADDRESS
              value: "{{ .Values.app.state_contract_address }}"
            - name: COMMIT_INTERVAL
              value: "{{ .Values.app.commit_interval }}"
      volumes:
        - name: "{{ .Release.Name }}-committer-volume"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-committer-claim"
