[package]
name = "utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
alloy = { workspace = true, features = ["consensus", "eips"] }
# TODO: is this a prod dep
c-kzg = { workspace = true }
# TODO: contemplate a custom err
anyhow = { workspace = true }
# TODO: minimize features
bitvec = { workspace = true, features = ["default"] }
serde = { workspace = true }
flate2 = { workspace = true, features = ["default"] }

[dev-dependencies]
proptest = { workspace = true, features = ["default"] }
alloy = { workspace = true, features = ["consensus", "eips", "kzg"] }
itertools = { workspace = true, features = ["use_alloc"] }
rand = { workspace = true, features = ["std", "std_rng", "small_rng"] }
test-case = { workspace = true }
